<?php
namespace App\Http\Controllers\LandingPage;
class Countries{


    public function countries(){

        $countries = [
            'Afghanistan',
            'Åland Islands',
            'Albania',
            'Algeria',
            'American Samoa',
            'Andorra',
            'Angola',
            'Anguilla',
            'Antarctica',
            'Antigua and Barbuda',
            'Argentina',
            'Armenia',
            'Aruba',
            'Australia',
            'Austria',
            'Azerbaijan',
            'Bahamas',
            'Bahrain',
            'Bangladesh',
            'Barbados',
            'Belarus',
            'Belgium',
            'Belize',
            'Benin',
            'Bermuda',
            'Bhutan',
            'Bolivia (Plurinational State of)',
            'Bosnia and Herzegovina',
            'Botswana',
            'Bouvet Island',
            'Brazil',
            'British Indian Ocean Territory',
            'Brunei Darussalam',
            'Bulgaria',
            'Burkina Faso',
            'Burundi',
            'Cabo Verde',
            'Cambodia',
            'Cameroon',
            'Canada',
            'Caribbean Netherlands',
            'Cayman Islands',
            'Central African Republic',
            'Chad',
            'Chile',
            'China',
            'Christmas Island',
            'Cocos (Keeling) Islands',
            'Colombia',
            'Comoros',
            'Congo',
            'Congo, Democratic Republic of the',
            'Cook Islands',
            'Costa Rica',
            'Croatia',
            'Cuba',
            'Curaçao',
            'Cyprus',
            'Czech Republic',
            'Côte d\'Ivoire',
            'Denmark',
            'Djibouti',
            'Dominica',
            'Dominican Republic',
            'Ecuador',
            'Egypt',
            'El Salvador',
            'Equatorial Guinea',
            'Eritrea',
            'Estonia',
            'Eswatini (Swaziland)',
            'Ethiopia',
            'Falkland Islands (Malvinas)',
            'Faroe Islands',
            'Fiji',
            'Finland',
            'France',
            'French Guiana',
            'French Polynesia',
            'French Southern Territories',
            'Gabon',
            'Gambia',
            'Georgia',
            'Germany',
            'Ghana',
            'Gibraltar',
            'Greece',
            'Greenland',
            'Grenada',
            'Guadeloupe',
            'Guam',
            'Guatemala',
            'Guernsey',
            'Guinea',
            'Guinea-Bissau',
            'Guyana',
            'Haiti',
            'Heard Island and Mcdonald Islands',
            'Honduras',
            'Hong Kong',
            'Hungary',
            'Iceland',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Ireland',
            'Isle of Man',
            'Israel',
            'Italy',
            'Jamaica',
            'Japan',
            'Jersey',
            'Jordan',
            'Kazakhstan',
            'Kenya',
            'Kiribati',
            'Korea, North',
            'Korea, South',
            'Kosovo',
            'Kuwait',
            'Kyrgyzstan',
            'Lao People\'s Democratic Republic',
            'Latvia',
            'Lebanon',
            'Lesotho',
            'Liberia',
            'Libya',
            'Liechtenstein',
            'Lithuania',
            'Luxembourg',
            'Macao',
            'Macedonia North',
            'Madagascar',
            'Malawi',
            'Malaysia',
            'Maldives',
            'Mali',
            'Malta',
            'Marshall Islands',
            'Martinique',
            'Mauritania',
            'Mauritius',
            'Mayotte',
            'Mexico',
            'Micronesia',
            'Moldova',
            'Monaco',
            'Mongolia',
            'Montenegro',
            'Montserrat',
            'Morocco',
            'Mozambique',
            'Myanmar (Burma)',
            'Namibia',
            'Nauru',
            'Nepal',
            'Netherlands',
            'Netherlands Antilles',
            'New Caledonia',
            'New Zealand',
            'Nicaragua',
            'Niger',
            'Nigeria',
            'Niue',
            'Norfolk Island',
            'Northern Mariana Islands',
            'Norway',
            'Oman',
            'Pakistan',
            'Palau',
            'Palestine',
            'Panama',
            'Papua New Guinea',
            'Paraguay',
            'Peru',
            'Philippines',
            'Pitcairn Islands',
            'Poland',
            'Portugal',
            'Puerto Rico',
            'Qatar',
            'Reunion',
            'Romania',
            'Russian Federation',
            'Rwanda',
            'Saint Barthelemy',
            'Saint Helena',
            'Saint Kitts and Nevis',
            'Saint Lucia',
            'Saint Martin',
            'Saint Pierre and Miquelon',
            'Saint Vincent and the Grenadines',
            'Samoa',
            'San Marino',
            'Sao Tome and Principe',
            'Saudi Arabia',
            'Senegal',
            'Serbia',
            'Serbia and Montenegro',
            'Seychelles',
            'Sierra Leone',
            'Singapore',
            'Sint Maarten',
            'Slovakia',
            'Slovenia',
            'Solomon Islands',
            'Somalia',
            'South Africa',
            'South Georgia and the South Sandwich Islands',
            'South Sudan',
            'Spain',
            'Sri Lanka',
            'Sudan',
            'Suriname',
            'Svalbard and Jan Mayen',
            'Sweden',
            'Switzerland',
            'Syria',
            'Taiwan',
            'Tajikistan',
            'Tanzania',
            'Thailand',
            'Timor-Leste',
            'Togo',
            'Tokelau',
            'Tonga',
            'Trinidad and Tobago',
            'Tunisia',
            'Turkey (Türkiye)',
            'Turkmenistan',
            'Turks and Caicos Islands',
            'Tuvalu',
            'U.S. Outlying Islands',
            'Uganda',
            'Ukraine',
            'United Arab Emirates',
            'United Kingdom',
            'United States',
            'Uruguay',
            'Uzbekistan',
            'Vanuatu',
            'Vatican City Holy See',
            'Venezuela',
            'Vietnam',
            'Virgin Islands, British',
            'Virgin Islands, U.S',
            'Wallis and Futuna',
            'Western Sahara',
            'Yemen',
            'Zambia',
            'Zimbabwe'
        ];

        return $countries;
        
    }

    public function cities() {
        $cities = [
            'Kabul',
            'Mariehamn',
            'Tirana',
            'Algiers',
            'Pago Pago',
            'Andorra la Vella',
            'Luanda',
            'The Valley',
            'McMurdo Station',
            'Saint John\'s',
            'Buenos Aires',
            'Yerevan',
            'Oranjestad',
            'Sydney',
            'Vienna',
            'Baku',
            'Nassau',
            'Manama',
            'Dhaka',
            'Bridgetown',
            'Minsk',
            'Brussels',
            'Belmopan',
            'Porto-Novo',
            'Hamilton',
            'Thimphu',
            'La Paz',
            'Sarajevo',
            'Gaborone',
            'Bouvet Island',
            'Brasilia',
            'Diego Garcia',
            'Bandar Seri Begawan',
            'Sofia',
            'Ouagadougou',
            'Gitega',
            'Praia',
            'Phnom Penh',
            'Yaoundé',
            'Ottawa',
            'Kralendijk',
            'George Town',
            'Bangui',
            'N\'Djamena',
            'Santiago',
            'Beijing',
            'Flying Fish Cove',
            'West Island',
            'Bogotá',
            'Moroni',
            'Brazzaville',
            'Kinshasa',
            'Avarua',
            'San José',
            'Zagreb',
            'Havana',
            'Willemstad',
            'Nicosia',
            'Prague',
            'Yamoussoukro',
            'Copenhagen',
            'Djibouti',
            'Roseau',
            'Santo Domingo',
            'Quito',
            'Cairo',
            'San Salvador',
            'Malabo',
            'Asmara',
            'Tallinn',
            'Mbabane',
            'Addis Ababa',
            'Stanley',
            'Tórshavn',
            'Suva',
            'Helsinki',
            'Paris',
            'Cayenne',
            'Papeete',
            'Port-aux-Français',
            'Libreville',
            'Banjul',
            'Tbilisi',
            'Berlin',
            'Accra',
            'Gibraltar',
            'Athens',
            'Nuuk',
            'St. George\'s',
            'Basse-Terre',
            'Hagåtña',
            'Guatemala City',
            'Gaza',
            'Jerusalem',
            'Jenin',
            'Ramallah',
            'St. Peter Port',
            'Conakry',
            'Bissau',
            'Georgetown',
            'Port-au-Prince',
            'Heard Island',
            'Tegucigalpa',
            'Hong Kong',
            'Budapest',
            'Reykjavik',
            'New Delhi',
            'Jakarta',
            'Tehran',
            'Baghdad',
            'Dublin',
            'Douglas',
            'Jerusalem',
            'Rome',
            'Kingston',
            'Tokyo',
            'Saint Helier',
            'Amman',
            'Nur-Sultan',
            'Nairobi',
            'Tarawa',
            'Pyongyang',
            'Seoul',
            'Pristina',
            'Kuwait City',
            'Bishkek',
            'Vientiane',
            'Riga',
            'Beirut',
            'Maseru',
            'Monrovia',
            'Tripoli',
            'Vaduz',
            'Vilnius',
            'Luxembourg',
            'Macao',
            'Skopje',
            'Antananarivo',
            'Lilongwe',
            'Kuala Lumpur',
            'Malé',
            'Bamako',
            'Valletta',
            'Majuro',
            'Fort-de-France',
            'Nouakchott',
            'Port Louis',
            'Mamoudzou',
            'Mexico City',
            'Palikir',
            'Chișinău',
            'Monaco',
            'Ulaanbaatar',
            'Podgorica',
            'Brades',
            'Rabat',
            'Maputo',
            'Naypyidaw',
            'Windhoek',
            'Yaren',
            'Kathmandu',
            'Amsterdam',
            'Willemstad',
            'Nouméa',
            'Wellington',
            'Managua',
            'Niamey',
            'Abuja',
            'Alofi',
            'Kingston',
            'Saipan',
            'Oslo',
            'Muscat',
            'Islamabad',
            'Ngerulmud',
            'Jerusalem',
            'Panama City',
            'Port Moresby',
            'Asunción',
            'Lima',
            'Manila',
            'Adamstown',
            'Warsaw',
            'Lisbon',
            'San Juan',
            'Doha',
            'Saint-Denis',
            'Bucharest',
            'Moscow',
            'Kigali',
            'Gustavia',
            'Jamestown',
            'Basseterre',
            'Castries',
            'Marigot',
            'Saint-Pierre',
            'Kingstown',
            'Apia',
            'San Marino',
            'São Tomé',
            'Riyadh',
            'Dakar',
            'Belgrade',
            'Podgorica',
            'Victoria',
            'Freetown',
            'Singapore',
            'Philipsburg',
            'Bratislava',
            'Ljubljana',
            'Honiara',
            'Mogadishu',
            'Pretoria',
            'King Edward Point',
            'Juba',
            'Madrid',
            'Sri Jayawardenepura Kotte',
            'Khartoum',
            'Paramaribo',
            'Longyearbyen',
            'Stockholm',
            'Bern',
            'Damascus',
            'Taipei',
            'Dushanbe',
            'Dodoma',
            'Bangkok',
            'Dili',
            'Lomé',
            'Fakaofo',
            'Nuku\'alofa',
            'Port of Spain',
            'Tunis',
            'Ankara',
            'Ashgabat',
            'Cockburn Town',
            'Funafuti',
            'Washington, D.C.',
            'Kampala',
            'Kyiv',
            'Abu Dhabi',
            'London',
            'New York',
            'Montevideo',
            'Tashkent',
            'Port Vila',
            'Vatican City',
            'Caracas',
            'Hanoi',
            'Road Town',
            'Charlotte Amalie',
            'Mata-Utu',
            'Laâyoune',
            'Sana\'a',
            'Lusaka',
            'Harare'
        ];
        return $cities;
    }

}



